### ISSUE TITLE
App keeps crashing for devices with API<21 giving the following Fatal error.

### ISSUE THREAD

**Issue by ys-git** [ys-git/Weatherping_2#2]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: app.ys.weatherping_2, PID: 2948
                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{app.ys.weatherping_2/app.ys.weatherping_2.Splashload}: android.view.InflateException: Binary XML file line #0: Error inflating class android.widget.ImageView
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                        at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:135)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                     Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class android.widget.ImageView
                                                                        at android.view.LayoutInflater.createView(LayoutInflater.java:633)
                                                                        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
                                                                        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:378)
                                                                        at android.app.Activity.setContentView(Activity.java:2145)
                                                                        at app.ys.weatherping_2.Splashload.onCreate(Splashload.java:19)
                                                                        at android.app.Activity.performCreate(Activity.java:5990)
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                        at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:135) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                                                                     Caused by: java.lang.reflect.InvocationTargetException
                                                                        at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                        at android.view.LayoutInflater.createView(LayoutInflater.java:607)
                                                                        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55) 
                                                                        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682) 
                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741) 
                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:378) 
                                                                        at android.app.Activity.setContentView(Activity.java:2145) 
                                                                        at app.ys.weatherping_2.Splashload.onCreate(Splashload.java:19) 
                                                                        at android.app.Activity.performCreate(Activity.java:5990) 
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278) 
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                        at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:135) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                                                                     Caused by: android.content.res.Resources$NotFoundException: Resource "app.ys.weatherping_2:drawable/weather1" (7f07008b)  is not a Drawable (color or path): TypedValue{t=0x1/d=0x7f07008b a=-1 r=0x7f07008b}
                                                                        at android.content.res.Resources.loadDrawableForCookie(Resources.java:2441)
                                                                        at android.content.res.Resources.loadDrawable(Resources.java:2381)
                                                                        at android.content.res.TypedArray.getDrawable(TypedArray.java:749)
                                                                        at android.widget.ImageView.<init>(ImageView.java:146)
                                                                        at android.widget.ImageView.<init>(ImageView.java:135)
                                                                        at android.widget.ImageView.<init>(ImageView.java:131)
                                                                        at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                        at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                                        at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
                                                                        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55) 
                                                                        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682) 
                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741) 
                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:378) 
                                                                        at android.app.Activity.setContentView(Activity.java:2145) 
                                                                        at app.ys.weatherping_2.Splashload.onCreate(Splashload.java:19) 
                                                                        at android.app.Activity.performCreate(Activity.java:5990) 
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278) 
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                        at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:135) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by ys-git** [comment]
Issue was fixed by upgrading the API level value.
